services:
  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coursejdbc
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=1234567

volumes:
  db-data:
    external: false